import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";
import SectionCards from "../components/card/section-cards";
import {getPopularVideos, getVideos} from "../lib/videos";

export async function getServerSideProps() {
    const disneyVideos = await getVideos("disney trailer");
    const travelVideos = await getVideos("Indie music");
    const productivityVideos = await getVideos("Productivity");
    const popularVideos = await getPopularVideos("popular");
    // console.log({disneyVideos})
    return {
        props: {disneyVideos, travelVideos, productivityVideos, popularVideos}
    }
}

export default function Home({disneyVideos, travelVideos, productivityVideos, popularVideos}) {

    return (
        <div className={styles.container}>
            <Head>
                <title>Netflix</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.main}>
                <NavBar username={'luca@sunnyday.software'}/>
                <Banner title="Clifford the red dog" subTitle="A very nice dog" imgUrl="/static/clifford.jpg"/>

                <div className={styles.sectionWrapper}>
                    <SectionCards title={"Disney"} videos={disneyVideos} size={"large"}/>
                    <SectionCards title={"Travel"} videos={travelVideos} size={"medium"}/>
                    <SectionCards title={"Productivity"} videos={productivityVideos} size={"medium"}/>
                    <SectionCards title={"Popular"} videos={popularVideos} size={"small"}/>
                </div>
            </div>
        </div>
    )
}
