import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";
import SectionCards from "../components/card/section-cards";
import {getPopularVideos, getVideos} from "../lib/videos";

export async function getServerSideProps() {
    const disneyVideos = await getVideos("dota2");
    const travelVideos = await getVideos("Indie music");
    const productivityVideos = await getVideos("Productivity");
    const popularVideos = await getPopularVideos("popular");
    // console.log({disneyVideos})
    return {
        props: {disneyVideos, travelVideos, productivityVideos, popularVideos}
    }
}

export default function Home({disneyVideos, travelVideos, productivityVideos, popularVideos}) {

    const getUsername = () => {

    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Netflix</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.main}>
                <NavBar username={'luca@sunnyday.software'}/>
                {/*<video src={"https://strapi.sunnyday.software/uploads/Studio_Legale_Mattiazzo_Firefox_Developer_Edition_2022_07_15_17_31_16_638cb1d142.mp4?updated_at=2022-07-20T08:31:26.738Z"} autoPlay></video>*/}
                <Banner title="Clifford the red dog" subTitle="A very nice dog" imgUrl="/static/clifford.jpg"/>

                <div className={styles.sectionWrapper}>
                    <SectionCards title={"Disney"} videos={disneyVideos} size={"large"}/>
                    <SectionCards title={"Travel"} videos={travelVideos} size={"medium"}/>
                    <SectionCards title={"Productivity"} videos={productivityVideos} size={"medium"}/>
                    <SectionCards title={"Popular"} videos={popularVideos} size={"small"}/>
                </div>
            </div>
        </div>
    )
}
